# npmjs registry 퍼블리시
name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    #     jest electron 이 macos아니면 오류가 나네요(멈춤)
    #     runs-on: ubuntu-latest
    runs-on: macOS-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          #           registry-url: "https://npm.pkg.github.com"
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.3.0
      - run: pnpm install
      - run: pnpm pre-publish
      - name: remove demo
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./demo
      - name: remove storybook-static
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./storybook-static
      - name: remove test
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./__tests__
      - name: remove how-to-use
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./dist/src/how-to-use
      - name: remove src
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./src

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
    needs: publish
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 'Determine tag'
        run: 'echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV'

      - name: 'Create release'
        uses: 'actions/github-script@v5'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
