# npmjs registry 퍼블리시
name: publish

on:
  push:
    branches:
      - 'release/**'

jobs:
  publish:
    runs-on: macOS-latest
    permissions: write-all
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated Release by GitHub Action CI
          draft: false
          prerelease: false
