# npmjs registry 퍼블리시
name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    #     jest electron 이 macos아니면 오류가 나네요(멈춤)
    #     runs-on: ubuntu-latest
    runs-on: macOS-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          #           registry-url: "https://npm.pkg.github.com"
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.3.0
      - run: pnpm install
      - run: pnpm pre-publish
      - name: remove demo
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./demo
      - name: remove storybook-static
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./storybook-static
      - name: remove test
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./__tests__
      - name: remove src
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./src

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
    needs: publish
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.current-version}}
          release_name: Release ${{ steps.package-version.outputs.current-version}}🌈
          body: |
            https://www.npmjs.com/package/heybit-ui-styled-components 에서 릴리즈 정보를 확인하세요.
          draft: false
          prerelease: false
